### ISSUE TITLE
Bluetooth printer not discovered on android 12+

### ISSUE THREAD

**Issue by top-kat** [tr3v3r/react-native-esc-pos-printer#85] opened 2023-01-12 14:39 UTC
Hi, 
Thanks a lot for such a great lib 👍 

On my android phone and the emulator (sdk v30) printing works fine. But when I try on a tablet (v32) and emulator (v33), the app quit unexpectedly when the discover function is called.

This is exactly where the code stops working:

![Pos Printer Bug](https://user-images.githubusercontent.com/17770809/212094755-c7a2eece-fe54-4172-90c4-419f4375614e.png)

Unfortunately I cannot investigate further since I tried multiple solutions to log from the `EscPosPrinterDiscoveryModule.java` file with no success...

I think this easily reproducible since you just need to run the code on emulator with adroid SDK v32+

Please tell me if I can do anything else

**EDIT**: I managed to log into the java file and isolated the line responsible of the crash: 

![Bug Printer 2](https://user-images.githubusercontent.com/17770809/212103156-7bd48c1e-4fb9-4bf8-bf6a-a91cbc82b8e9.png)

The error IS NOT catched...

**Comment by karaushu** [comment] 2023-01-18 11:13
For Android 12 need to request permissions for BLUETOOTH_CONNECT and BLUETOOTH_SCAN before discover.

**Comment by top-kat** [comment] 2023-01-18 12:58
Hi, here is the list of permissions I am using in `android/app/src/main/AndroidManifest.xml`:

``` xml 
  <uses-permission-sdk-23 android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.BLUETOOTH"/>
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

I have both of them, did I miss something @karaushu  ?

**Comment by karaushu** [comment] 2023-01-18 13:07
1. Try to turn off Bluetooth and then discover, if there there is no crash then preaty sure the problem is with BLE permissions.
2. If there is no crash then try to request permissions before discovery. Eg:
```js
await PermissionsAndroid.request(
  'android.permission.BLUETOOTH_CONNECT'
);
await PermissionsAndroid.request(
  'android.permission.BLUETOOTH_SCAN'
);
```
And also it may require `FINE_LOCATION` 
```js
const status = await PermissionsAndroid.request(
  'android.permission.ACCESS_FINE_LOCATION'
);
```
And after all accesses try `PosPrinter.discover`

**Comment by top-kat** [comment] 2023-01-18 13:08
Thanks a lot, I'll try that 👍

**Comment by top-kat** [comment] 2023-01-18 13:39
Hi, I cannot reproduce the exact crash for the moment. You may be true since the crash was happening on expo development version of the app. When I build the app, the app doesn't crash, but **the problem still persists**:

Some details: with the same phone, on android 11 I was able to print via bluetooth. But since I updated my android phone to V12 it stopped working and the printer is not found. 
I have tested with multiples devices, all with bluetooth activated. Printing via wifi works fine though.

I will update the title of the issue to better match this description. Thanks a lot for your time :)

**Comment by karaushu** [comment] 2023-01-18 13:42
Anyway to discover you will need to ask those permissions

**Comment by top-kat** [comment] 2023-01-18 17:07
Hi, you were right! Thanks to you my code is working now!

Some questions however:
* Why I need to explicitly ask for permissions, I thought the lib was doing it as I saw in the code ?
* Why also it looks like it asks me location permission (with the image of a map) ?

Thanks you very much again!

**Comment by karaushu** [comment] 2023-01-19 08:12
First of all, i'm not a lib dev :) so idk about third one.
1. Lib do it, but in Android 12+ permissions API have some major changes. If you will read [docs](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions) you will see that new request has been added
2. Needed only if your app uses Bluetooth scan results to derive physical location. You can avoid this by adding that [flag](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location)

**Comment by tr3v3r** [comment] 2023-01-25 14:59
Thanks @karaushu!
And I suppose all this described in the installation docs
https://github.com/tr3v3r/react-native-esc-pos-printer/blob/main/docs/INSTALLATION.md

Or I missed simething?

cc: @top-kat

**Comment by tr3v3r** [comment] 2023-01-31 20:47
@top-kat  Thanks for explanation!
Indeed sometimes Android require explicit permission request 
I'll add it to installation section

**Comment by tr3v3r** [comment] 2023-01-31 21:01
@top-kat  @karaushu  btw just found that Epson sdk was released and it should be fixed there
<img width="559" alt="image" src="https://user-images.githubusercontent.com/23724142/215882188-ddb0f245-9bec-4ef3-8bc0-51b7868230da.png">

I'm going to update SDK soon for this lib

**Comment by top-kat** [comment] 2023-02-01 08:57
Ok, I'll be glad to help you test the next release :) Keep me updated

**Comment by lufke** [comment] 2023-02-14 12:59
Hi

I tried the example from this repo, added the permissions detailed here on the Manifest and before call the discover method, but always I get and empty list of printers.
I have paired a MPT-II Bluetooth printer on my phone (Motorola G71, Android 12)

```
          <Button
          title='SEARCH PRINTERS'
          onPress={async () => {
            try {
              const btConnect = await PermissionsAndroid.request('android.permission.BLUETOOTH_CONNECT');
              const btScan = await PermissionsAndroid.request('android.permission.BLUETOOTH_SCAN');
              const fineLocation = await PermissionsAndroid.request('android.permission.ACCESS_FINE_LOCATION');
              const printers = await EscPosPrinter.discover({ scanningTimeoutAndroid: 10000 });
              console.log({ btConnect, btScan, fineLocation, printers });
            } catch (error) {
              console.error(error)
            }
          }
          }
        />
```



this is my console

![image](https://user-images.githubusercontent.com/28881274/218742841-6d5e7024-b75b-476a-901e-414ed5547b30.png)


I don't know what I'm missing, any ideas? Thansk in advice

**Comment by tr3v3r** [comment] 2023-02-16 09:21
@lufke Hi!
It seems that your printer was not produced by Epson right?
This lib supports only  EPSON TM printers

**Comment by tr3v3r** [comment] 2023-02-16 10:02
@top-kat hey!
Just release a new version with the latest SDK.
I'd really appreciate it if you could check Android stuff at your earliest convenience

**Comment by lufke** [comment] 2023-02-16 11:51
> @lufke Hi!
> It seems that your printer was not produced by Epson right?
> This lib supports only  EPSON TM printers 

That's correct. Thanks for tour answer

**Comment by top-kat** [comment] 2023-02-17 11:09
@tr3v3r it solved the crash problem! I tested without the additional permissions lines and it still asked me for permissions. So no more crash also and no more silent crash on emulator 👍 

Anyway, the problem persists, I was not able to make the bluetooth printer recognized without adding those two extra lines to grant permission outside of the lib, so **they are still needed for the code to work properly**.

Tell me if you need further details.

**Closed** 2023-02-18 17:20 UTC

**Comment by tr3v3r** [comment] 2023-03-26 19:37
@top-kat in 2.5, this run time permissions will be requested by the lib itself
https://github.com/tr3v3r/react-native-esc-pos-printer/commit/06b670926be8a4a3ef8044be934024218e52b5a4
