### ISSUE TITLE
  [Android] Hermes engine,  Cannot read property EscPostPrinter.getConstants() of null

### ISSUE THREAD

**Issue by karaushu** [tr3v3r/react-native-esc-pos-printer#186] opened 2024-10-11 15:53 UTC
### Description

After upgrading to EXPO 51 with React Native 0.74.5 got error
` TypeError: Cannot read property 'getConstants' of null, js engine: hermes`.
Debbuger says error is in constants.ts at line 16:
`export const nativeConstants = EscPostPrinter.getConstants();`
react-native-esc-pos-printer version ^3.1.1 and 4.2.0

### Steps to reproduce

1. Create expo dev client with react-native-esc-pos-printer package;
2. Import and use EscPostPrinter;

### react-native-esc-pos-printer version

4.2.0

### React Native version

0.74.5

### Platforms

Android

### Workflow

Expo Dev Client

### Architecture

None

### Build type

Debug app & production bundle

### Device

Real device

### Device model

Bunch of devices with andrtoid 9, 12, 13, 14 

### Acknowledgements

Yes

**Comment by Sarorn123** [comment] 2024-10-13 10:05
> ### Description
> After upgrading to EXPO 51 with React Native 0.74.5 got error ` TypeError: Cannot read property 'getConstants' of null, js engine: hermes`. Debbuger says error is in constants.ts at line 16: `export const nativeConstants = EscPostPrinter.getConstants();` react-native-esc-pos-printer version ^3.1.1 and 4.2.0
> 
> ### Steps to reproduce
> 1. Create expo dev client with react-native-esc-pos-printer package;
> 2. Import and use EscPostPrinter;
> 
> ### react-native-esc-pos-printer version
> 4.2.0
> 
> ### React Native version
> 0.74.5
> 
> ### Platforms
> Android
> 
> ### Workflow
> Expo Dev Client
> 
> ### Architecture
> None
> 
> ### Build type
> Debug app & production bundle
> 
> ### Device
> Real device
> 
> ### Device model
> Bunch of devices with andrtoid 9, 12, 13, 14
> 
> ### Acknowledgements
> Yes

me too

**Comment by tr3v3r** [comment] 2024-10-14 10:57
I think you're doing something wrong. I just created a bare expo project and run it on Android.

1) npx create-expo-app@latest testexp
2) update app.json
<img width="640" alt="image" src="https://github.com/user-attachments/assets/881a6c13-51b0-4c8b-ab27-79718f9f3b9d">

3) npx expo install react-native-esc-pos-printer
4) npx expo prebuild   
5) run the following code

<img width="871" alt="image" src="https://github.com/user-attachments/assets/4d92b801-10d5-4d28-8e8c-cb0d6d8d13aa">

Output: 
<img width="1990" alt="image" src="https://github.com/user-attachments/assets/4dc5df04-c632-4389-bbb9-f5b664b2321b">

The app runs without any issues.

<img width="734" alt="image" src="https://github.com/user-attachments/assets/fa9a9ea8-f91a-4f01-96f9-d71ae44341e5">


I'm closing it for now. If you're about to reopen it, please create a reproducible repo so I can check.

**Closed by tr3v3r** 2024-10-14 10:57 UTC

**Comment by Sarorn123** [comment] 2024-10-14 12:10
<img width="596" alt="image" src="https://github.com/user-attachments/assets/7424045e-e761-4e17-8f06-888364313611">

**Comment by Sarorn123** [comment] 2024-10-14 12:11
i try to follow you but it not work.

**Comment by tr3v3r** [comment] 2024-10-14 12:19
How did you run it? Have you tried emulatator?

**Comment by Sarorn123** [comment] 2024-10-14 13:13
i use my cable to my real device and try run prebuild then run start -c

**Comment by tr3v3r** [comment] 2024-10-14 13:25
@Sarorn123  which command do you use for bundling?
try 
`npx expo run:android --device`

and select your device

**Comment by Sarorn123** [comment] 2024-10-15 03:36
thank i will try

**Comment by karaushu** [comment] 2024-11-01 10:12
So in my case trouble was that library was in optionalDependencies in package.json. becasue web version fails to build is library is presented in deps, but react-native fails to pick up optionalDependencies.
Maybe @tr3v3r you have any suggestion? 
Sorry for taking your time on misleading issue.

**Comment by fajardwiutomo** [comment] 2024-12-27 06:51
i got same problem, I follow every step, but still get null.
maybe because version expo latest? now version 52, on that picture version expo 51

**Comment by alexsvt2** [comment] 2025-01-09 06:23
/

> i got same problem, I follow every step, but still get null. maybe because version expo latest? now version 52, on that picture version expo 51

Hi @fajardwiutomo  

Did you find the issue ?
