### ISSUE TITLE
Android EscPosPrinter.printing() takes too long if IP address is not correct

### ISSUE THREAD

**Issue by ahaikal** [tr3v3r/react-native-esc-pos-printer#42] opened 2021-12-23 18:01 UTC
Hi

When i try to connect to a printer using a wrong IP address, as in 
```
const response = await EscPosPrinter.init({
  target: `TCP:123.123.132.123`,
  seriesName: sourceName,
  language: 'EPOS2_LANG_EN',
})

const printingStatus = await printing
  .initialize()
  .cut()
  .send();
```

```
12-24 02:15:11.456 13965 13973 E AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
12-24 02:15:11.456 13965 13973 E AndroidRuntime: Process: com.pos.pos, PID: 13965
12-24 02:15:11.456 13965 13973 E AndroidRuntime: java.util.concurrent.TimeoutException: com.epson.epos2.printer.Printer.finalize() timed out after 10 seconds
12-24 02:15:11.456 13965 13973 E AndroidRuntime:  at com.epson.epos2.printer.Printer.nativeEpos2Disconnect(Native Method)
12-24 02:15:11.456 13965 13973 E AndroidRuntime:  at com.epson.epos2.printer.Printer.finalize()
12-24 02:15:11.456 13965 13973 E AndroidRuntime:  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
12-24 02:15:11.456 13965 13973 E AndroidRuntime:  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
12-24 02:15:11.456 13965 13973 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:818)
```

it takes too long trying to connect to that address. and some times it crashes the app.

This's only happening on android.

**Comment by tr3v3r** [comment] 2021-12-24 06:56
Hi! Thanks for reporting an issue!
I'll take a look into it asap.

**Comment by naufalprakoso** [comment] 2022-01-03 03:53
I also have a similar problem.

**Comment by naufalprakoso** [comment] 2022-01-03 17:28
I also have a similar problem. I think the problem is from the Epson Android SDK. I asked the same question in StackOverflow, waiting for the answer from everyone.
https://stackoverflow.com/questions/70569386/epson-android-sdk-com-epson-epos2-printer-printer-finalize-timed-out

**Comment by naufalprakoso** [comment] 2022-01-15 01:56
Update:
This issue will be fixed by Epson in SDK V2.20. Don't forget to check regularly on this site: https://download.epson-biz.com/modules/pos/index.php?page=soft&scat=61

**Comment by tr3v3r** [comment] 2022-01-15 12:51
@naufalprakoso thanks for help! As soon as Epson release new SDK I’ll update library as well!

**Comment by tr3v3r** [comment] 2022-03-24 10:13
@naufalprakoso  Updated to SDK v2.20 both for Android and iOS. Please check release 1.11.0

**Closed by tr3v3r** 2022-03-24 10:13 UTC

**Comment by Rishvik-Uber** [comment] 2025-08-16 08:46
@tr3v3r I'm still facing this issue in v2.28. Any help will be appreciable. Thanks.
